### ISSUE TITLE
Include requirements in README

### ISSUE THREAD

**Issue by lagzda** [metaDAOproject/meta-dao#23]
It might be worth adding some install instructions with some common gotchas, for example for me it said - 

`error: package `regex-automata v0.4.3` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.62.0-dev`

In addition to updating rust you should also update solana version on your machine - 

`solana-install init 1.16.18`

**Comment by metaproph3t** [comment]
Solved by #25
